# Generated by Django 5.1.5 on 2025-01-26 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_user_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(blank=True, choices=[('music', 'Music Instrument'), ('art', 'Art'), ('electronics', 'Electronics'), ('fashion', 'Fashion'), ('sports', 'Sports Equipment')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
